name: Auto Assigner
description: A GitHub Action to assign collaborators to issues and pull requests based on a configuration file.
author: Luca Ercole
branding:
  icon: users
  color: blue
inputs:
  repo-token:
    description: the authentication token provided by github
    # TODO check if this works
    default: ${{ secrets.GITHUB_TOKEN }}
    required: true
runs:
  using: node12
  main: dist/index.js
