name: Conventional Commits

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  commitsar:
    name: Check conformity to Conventional Commits specification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: run commitsar
        uses: outillage/commitsar@v0.9.0
