name: Conventional Commits

on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      - opened
      - reopened
      - synchronize # this triggers when pushing to the pr's branch
      - edited # this is needed for conventional-pr-title
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  commitsar:
    name: Check commits
    runs-on: ubuntu-latest

    # do not run when the trigger has not changed any commit
    if: github.event.action != 'edited'

    steps:
      # This does not work
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      - uses: actions/checkout@v1

      - name: run commitsar
        uses: outillage/commitsar@v0.9.0

  semantic-pr:
    name: Check PR title (BUGGED)
    runs-on: ubuntu-latest

    steps:
      - name: PR Title ok
        uses: amannn/action-semantic-pull-request@v1.1.1

  conventional-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest

    steps:
      - name: conventional-pr-title
        uses: aslafy-z/conventional-pr-title-action@v2.2.0
        # with:
        #   preset: "zzz"
