name: Build and Test

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

# TODO both jobs should only run when the lint check is a success
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          npm install
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./ # with the default input value
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
